silverstrike/urls.py
from django.urls import include, path
from django.views.generic import TemplateView

from rest_framework import routers

from silverstrike import api
from silverstrike.rest import views as rest_views
from silverstrike.views import account as account_views
from silverstrike.views import budgets as budget_views
from silverstrike.views import categories as category_views
from silverstrike.views import charts as chart_views
from silverstrike.views import imports as import_views
from silverstrike.views import index as general_views
from silverstrike.views import recurrences as recurrence_views
from silverstrike.views import transactions as transaction_views


router = routers.DefaultRouter()
router.register(r'accounts', rest_views.AccountViewSet)
router.register(r'transactions', rest_views.TransactionViewSet)
router.register(r'categories', rest_views.CategoryViewSet)
router.register(r'recurrences', rest_views.RecurringTransactionsViewset)

urlpatterns = [
    path('', general_views.IndexView.as_view(), name='index'),
    path('profile/', general_views.ProfileView.as_view(), name='profile'),

    path('auth/', include('allauth.urls')),

    path('transactions/', transaction_views.TransactionIndex.as_view(), name='transactions'),
    path('transactions/<int:pk>/',
         transaction_views.TransactionDetailView.as_view(), name='transaction_detail'),
    path('transactions/<int:pk>/update/',
         transaction_views.TransactionUpdateView.as_view(), name='transaction_update'),
    path('transactions/<int:pk>/split/',
         transaction_views.SplitUpdate.as_view(), name='split_update'),
    path('transactions/<int:pk>/delete/',
         transaction_views.TransactionDeleteView.as_view(), name='transaction_delete'),
    path('transactions/create/transfer/',
         transaction_views.TransactionCreate.as_view(), {'type': 'transfer'}, name='transfer_new'),
    path('transactions/create/withdraw/',
         transaction_views.TransactionCreate.as_view(), {'type': 'withdraw'}, name='withdraw_new'),
    path('transactions/create/deposit/',
         transaction_views.TransactionCreate.as_view(), {'type': 'deposit'}, name='deposit_new'),
    path('transactions/create/split/',
         transaction_views.SplitCreate.as_view(), name='split_create'),

    path('accounts/<int:pk>/update/',
         account_views.AccountUpdate.as_view(), name='account_update'),
    path('accounts/<int:pk>/delete/',
         account_views.AccountDelete.as_view(), name='account_delete'),
    path('accounts/<int:pk>/all',
         account_views.AccountView.as_view(), {'period': 'all'}, name='account_detail_all'),
    path('accounts/<int:pk>/<dstart>/<dend>/',
         account_views.AccountView.as_view(), {'period': 'custom'}, name='account_detail'),
    path('accounts/<int:pk>/', account_views.AccountView.as_view(), {'period': 'month'},
         name='account_view'),
    path('accounts/<int:pk>/reconcile/',
         account_views.ReconcileView.as_view(), name='account_reconcile'),

    path('accounts/new/', account_views.AccountCreate.as_view(), name='account_new'),

    path('accounts/',
         account_views.AccountIndex.as_view(), name='accounts'),

    path('recurrences/',
         recurrence_views.RecurringTransactionIndex.as_view(), name='recurrences'),
    path('recurrences/create/',
         recurrence_views.RecurrenceCreateView.as_view(), name='recurrence_create'),
    path('recurrences/<int:pk>/', recurrence_views.RecurrenceDetailView.as_view(),
         name='recurrence_detail'),
    path('recurrences/<int:pk>/update/', recurrence_views.RecurrenceUpdateView.as_view(),
         name='recurrence_update'),
    path('recurrences/<int:pk>/delete/', recurrence_views.RecurrenceDeleteView.as_view(),
         name='recurrence_delete'),
    path('recurrences/<int:pk>/transaction/create/',
         recurrence_views.RecurrenceTransactionCreateView.as_view(),
         name='recurrence_transaction_create'),


    path('categories/', category_views.CategoryIndex.as_view(), name='categories'),
    path('categories/inactive/', category_views.InactiveCategoriesView.as_view(),
         name='inactive_categories'),
    path('categories/month/<int:year>/<int:month>/', category_views.CategoryIndex.as_view(),
         name='categories_month'),
    path('categories/create/',
         category_views.CategoryCreateView.as_view(), name='category_create'),
    path('categories/<int:pk>/',
         category_views.CategoryDetailView.as_view(), name='category_detail'),
    path('categories/<int:pk>/<int:year>/<int:month>/',
         category_views.CategoryDetailView.as_view(), name='category_month'),
    path('categories/<int:pk>/delete/', category_views.CategoryDeleteView.as_view(),
         name='category_delete'),
    path('categories/<int:pk>/update/', category_views.CategoryUpdateView.as_view(),
         name='category_update'),

    path('budgets/', budget_views.BudgetIndex.as_view(), name='budgets'),
    path('budgets/<int:year>/<int:month>/',
         budget_views.BudgetIndex.as_view(), name='budget_month'),

    path('charts/', chart_views.ChartView.as_view(), name='charts'),

    path('api/accounts/<account_type>/', api.get_accounts, name='api_accounts'),
    path('api/balance/<dstart>/<dend>/', api.get_balances, name='api_balance'),
    path('api/accounts_balance/<dstart>/<dend>/',
         api.get_accounts_balance, name='api_accounts_balance'),
    path('api/category_spending/<dstart>/<dend>/',
         api.category_spending, name='category_spending'),

    path('manifest.json', TemplateView.as_view(template_name='silverstrike/manifest.json'),
         name='manifest'),

    path('import/', import_views.ImportView.as_view(), name='import'),
    path('import/firefly/', import_views.ImportFireflyView.as_view(), name='import_firefly'),
    path('import/generic/', import_views.ImportUploadView.as_view(), name='import_generic'),
    path('import/generic/<uuid:uuid>/', import_views.ImportConfigureView.as_view(),
         name='import_configure'),
    path('import/generic/<uuid:uuid>/process/<int:config_pk>/',
         import_views.ImportProcessView.as_view(), name='import_process'),

    path('export/', import_views.ExportView.as_view(), name='export'),

    path('rest/', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),

]

silverstrike/models.py
import uuid
from datetime import date, timedelta

from dateutil.relativedelta import relativedelta

from django.db import models
from django.urls import reverse
from django.utils.translation import ugettext as _


class Account(models.Model):
    PERSONAL = 1
    FOREIGN = 2
    SYSTEM = 3
    ACCOUNT_TYPES = (
        (PERSONAL, _('Personal')),
        (FOREIGN, _('Foreign')),
        (SYSTEM, _('System')),
    )

    name = models.CharField(max_length=64)
    account_type = models.IntegerField(choices=ACCOUNT_TYPES, default=PERSONAL)
    active = models.BooleanField(default=True)
    last_modified = models.DateTimeField(auto_now=True)
    show_on_dashboard = models.BooleanField(default=False)

    class Meta:
        ordering = ['-active', 'name']
        unique_together = (('name', 'account_type'),)

    def __str__(self):
        return self.name

    @property
    def account_type_str(self):
        return Account.ACCOUNT_TYPES[self.account_type - 1][1]

    @property
    def is_personal(self):
        return self.account_type == Account.PERSONAL

    @property
    def transaction_num(self):
        """
        TODO do we really want the number of splits?
        """
        return Split.objects.filter(account=self).count()

    @property
    def balance(self):
        return self.balance_on(date.today())

    def balance_on(self, date):
        return Split.objects.filter(account=self, date__lte=date).aggregate(
            models.Sum('amount'))['amount__sum'] or 0

    def get_absolute_url(self):
        return reverse('account_view', args=[self.pk])

    def get_data_points(self, dstart=date.today() - timedelta(days=365),
                        dend=date.today(), steps=30):
        step = (dend - dstart) / steps
        if step < timedelta(days=1):
            step = timedelta(days=1)
            steps = int((dend - dstart) / step)
        data_points = []
        balance = self.balance_on(dstart - timedelta(days=1))
        transactions = list(Split.objects.prefetch_related('transaction').filter(
            account_id=self.pk).date_range(dstart, dend).order_by(
            '-transaction__date'))
        for i in range(steps):
            while len(transactions) > 0 and transactions[-1].transaction.date <= dstart:
                t = transactions.pop()
                balance += t.amount
            data_points.append((dstart, balance))
            dstart += step
        for t in transactions:
            balance += t.amount
        data_points.append((dend, balance))
        return data_points

    def set_initial_balance(self, amount):
        system = Account.objects.get(account_type=Account.SYSTEM)
        transaction = Transaction.objects.create(title=_('Initial Balance'),
                                                 transaction_type=Transaction.SYSTEM)
        Split.objects.create(transaction=transaction, amount=-amount,
                             account=system, opposing_account=self)
        Split.objects.create(transaction=transaction, amount=amount,
                             account=self, opposing_account=system)


class TransactionQuerySet(models.QuerySet):
    def last_10(self):
        return self.order_by('-date')[:10]


class Transaction(models.Model):
    DEPOSIT = 1
    WITHDRAW = 2
    TRANSFER = 3
    SYSTEM = 4
    TRANSACTION_TYPES = (
        (DEPOSIT, 'Deposit'),
        (WITHDRAW, 'Withdrawl'),
        (TRANSFER, 'Transfer'),
        (SYSTEM, 'Reconcile'),
    )

    class Meta:
        ordering = ['-date', 'title']

    title = models.CharField(max_length=64)
    date = models.DateField(default=date.today)
    notes = models.TextField(blank=True, null=True)
    transaction_type = models.IntegerField(choices=TRANSACTION_TYPES)
    last_modified = models.DateTimeField(auto_now=True)
    recurrence = models.ForeignKey('RecurringTransaction', models.SET_NULL,
                                   related_name='recurrences', blank=True, null=True)

    objects = TransactionQuerySet.as_manager()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('transaction_detail', args=[self.pk])

    def get_transaction_type_str(self):
        for i, name in self.TRANSACTION_TYPES:
            if i == self.transaction_type:
                return name

    @property
    def amount(self):
        if self.transaction_type == Transaction.TRANSFER:
            return abs(
                self.splits.transfers_once().aggregate(models.Sum('amount'))['amount__sum'] or 0)
        else:
            return self.splits.personal().aggregate(models.Sum('amount'))['amount__sum'] or 0

    @property
    def is_split(self):
        return len(self.splits.all()) > 2

    @property
    def is_system(self):
        return self.transaction_type == self.SYSTEM

    @property
    def is_transfer(self):
        return self.transaction_type == self.TRANSFER

    @property
    def is_withdraw(self):
        return self.transaction_type == self.WITHDRAW

    @property
    def is_deposit(self):
        return self.transaction_type == self.DEPOSIT


class SplitQuerySet(models.QuerySet):
    def personal(self):
        return self.filter(account__account_type=Account.PERSONAL)

    def income(self):
        return self.filter(opposing_account__account_type=Account.FOREIGN, amount__gt=0)

    def expense(self):
        return self.filter(opposing_account__account_type=Account.FOREIGN, amount__lt=0)

    def date_range(self, dstart, dend):
        return self.filter(date__gte=dstart, date__lte=dend)

    def category(self, category):
        return self.filter(category=category)

    def transfers_once(self):
        return self.personal().exclude(opposing_account__account_type=Account.PERSONAL,
                                       amount__gte=0)

    def exclude_transfers(self):
        return self.exclude(account__account_type=Account.PERSONAL,
                            opposing_account__account_type=Account.PERSONAL)

    def upcoming(self):
        return self.filter(date__gt=date.today())

    def past(self):
        return self.filter(date__lte=date.today())

    def recurrence(self, recurrence_id):
        return self.filter(transaction__recurrence_id=recurrence_id)


class Split(models.Model):
    account = models.ForeignKey(Account, models.CASCADE, related_name='incoming_transactions')
    opposing_account = models.ForeignKey(Account, models.CASCADE,
                                         related_name='outgoing_transactions')
    title = models.CharField(max_length=64)
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    date = models.DateField(default=date.today)
    category = models.ForeignKey('Category', models.SET_NULL, blank=True, null=True,
                                 related_name='splits')
    transaction = models.ForeignKey(Transaction, models.CASCADE, related_name='splits',
                                    blank=True, null=True)
    last_modified = models.DateTimeField(auto_now=True)

    objects = SplitQuerySet.as_manager()

    class Meta:
        ordering = ['-date', 'title']

    def __str__(self):
        return self.title

    @property
    def is_transfer(self):
        return self.transaction.transaction_type == Transaction.TRANSFER

    @property
    def is_withdraw(self):
        return self.transaction.transaction_type == Transaction.WITHDRAW

    @property
    def is_deposit(self):
        return self.transaction.transaction_type == Transaction.DEPOSIT

    @property
    def is_system(self):
        return self.transaction.transaction_type == Transaction.SYSTEM

    def get_absolute_url(self):
        return self.transaction.get_absolute_url()


class Category(models.Model):
    name = models.CharField(max_length=64)
    active = models.BooleanField(default=True)
    last_modified = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    @property
    def money_spent(self):
        return abs(Split.objects.filter(
                category=self, account__account_type=Account.PERSONAL,
                transaction__transaction_type=Transaction.WITHDRAW).aggregate(
            models.Sum('amount'))['amount__sum'] or 0)

    def get_absolute_url(self):
        return reverse('category_detail', args=[self.id])


class BudgetQuerySet(models.QuerySet):
    def for_month(self, month):
        return self.filter(month=month)


class Budget(models.Model):
    category = models.ForeignKey(Category, models.CASCADE)
    month = models.DateField()
    amount = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    last_modified = models.DateTimeField(auto_now=True)

    objects = BudgetQuerySet.as_manager()


class ImportFile(models.Model):
    uuid = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    file = models.FileField(upload_to='imports')


class ImportConfiguration(models.Model):
    DO_NOT_USE = 0
    SOURCE_ACCOUNT = 1
    DESTINATION_ACCOUNT = 2
    AMOUNT = 3
    DATE = 4
    NOTES = 5
    CATEGORY = 6
    TITLE = 7

    FIELD_TYPES = (
        (DO_NOT_USE, _('Do not use')),
        (SOURCE_ACCOUNT, _('Source Account')),
        (DESTINATION_ACCOUNT, _('Destination Account')),
        (AMOUNT, _('Amount')),
        (DATE, _('Date')),
        (NOTES, _('Notes')),
        (CATEGORY, _('Category')),
        (TITLE, _('Title')),
        )

    name = models.CharField(max_length=64)
    headers = models.BooleanField(help_text=_('First line contains headers'))
    default_account = models.ForeignKey(Account, models.SET_NULL,
                                        limit_choices_to={'account_type': Account.PERSONAL},
                                        null=True, blank=True)
    dateformat = models.CharField(max_length=32)
    config = models.TextField()

    def __str__(self):
        return self.name


class RecurringTransactionManager(models.Manager):

silverstrike/views/charts.py
from datetime import date

from dateutil.relativedelta import relativedelta

from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import generic

from silverstrike.lib import last_day_of_month


class ChartView(LoginRequiredMixin, generic.TemplateView):
    template_name = 'silverstrike/charts.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['menu'] = 'charts'
        context['today'] = date.today()
        context['minus_3_months'] = date.today() - relativedelta(months=3)
        context['minus_6_months'] = date.today() - relativedelta(months=6)
        context['minus_12_months'] = date.today() - relativedelta(years=1)

        context['first_day_of_month'] = date.today().replace(day=1)
        context['last_day_of_month'] = last_day_of_month(date.today())
        return context

silverstrike/templates/silverstrike/account_confirm_delete.html
{% extends 'silverstrike/base.html' %}
{% load i18n %}
{% load widget_tweaks %}

{% block content_header %}
<h1>Delete '{{ object.name }}' account</h1>
{% endblock %}

{% block content %}
<div class="col-md-offset-3 col-md-6">
<div class="box">
  <form method="post" class="form-horizontal">
    <div class="box-body">
      {% csrf_token %}
        <p>
          {% blocktrans %}
          Are you sure you want to delete the account along with {{ object.transaction_num }} transactions?
          {% endblocktrans %}
        </p>
        <div class="text-center">
        <a href="{{ object.get_absolute_url }}" class="btn btn-default">{% trans 'Cancel' %}</a>
        <button type="submit" class="btn btn-danger">{% trans 'Delete' %}</button>
      </div>
    </div>
  </form>

</div>
</div>
{% endblock %}

silverstrike/templates/silverstrike/account_form.html
{% extends 'silverstrike/base.html' %}
{% load i18n %}
{% load widget_tweaks %}

{% block content_header %}
<h1>{% trans 'Accounts' %}
  {% if object %}
  <small>{% blocktrans %}Update {{ object.name }}{% endblocktrans %}</small>
  {% else %}
  <small>{% trans 'Create new account' %}</small>
  {% endif %}
</h1>
<ol class="breadcrumb">
  <li><a href="/">{% trans 'Home' %}</a></li>
  <li><a href="#">{% trans 'Accounts' %}</a></li>
  {% if object %}
  <li><a href="{{ object.get_absolute_url }}">{{ object }}</a></li>
  <li class="active">{% trans 'Update' %}</li>
  {% else %}
  <li class="active">{% trans 'New' %}</li>
  {% endif %}
</ol>
{% endblock %}

{% block content %}
<div class="box">
  <div class="box-header with-border">
    <h3 class="box-title">{% trans 'Account Details' %}</h3>
  </div>
  <form method="post" class="form-horizontal">
    <div class="box-body">
      {% csrf_token %}
      {% for field in form %}
      <div class="form-group">
        {% if field|widget_type != "checkboxinput" %}
        <label class="control-label col-sm-2" for="{{ field.id_for_label }}">{{ field.label }}</label>
        <div class="col-sm-8">
          {% render_field field placeholder=field.label class="form-control" %}
        </div>
        {% else %}
        <div class="col-sm-offset-2 col-sm-8 ">
          <div class="checkbox">
            <label>
              {{ field }}
              {{ field.label }}
            </label>
          </div>
        </div>
        {% endif %}
        {% for error in  field.errors %}
        <span class="help-block">{{ errror }}<span>
            {% endfor %}
      </div>
      {% endfor %}
    </div>
    <div class="box-footer">
      <div class="col-sm-offset-2 col-sm-8">
        {% if object %}
        <button type="submit" class="btn btn-primary">{% trans 'Update' %}</button>
        <a href="{{ account.get_absolute_url }}" class="btn btn-default">{% trans 'Cancel' %}</a>
        <a href="{% url 'account_delete' account.pk %}" class="btn btn-danger pull-right">{% trans 'Delete' %}</a>
        {% else %}
        <button type="submit" class="btn btn-primary">{% trans 'Create' %}</button>
        {% endif %}
      </div>
    </div>
  </form>

</div>
{% endblock %}

silverstrike/templates/silverstrike/newform.html
{% extends 'silverstrike/base.html' %}
{% load i18n %}
{% load static %}
{% load widget_tweaks %}

{% block content_header %}
<h1>Transactions
  <small>
  {% if object %}
  Edit {{ object.title }}
  {% else %}
  Add new {{ submenu }}
  {% endif %}
  </small>
</h1>
<ol class="breadcrumb">
<li><a href="/">Home</a></li>
<li><a href="{% url 'transactions' %}">Transactions</a></li>
{% if object %}
<li><a href="{{ object.get_absolute_url }}">{{ object }}</a></li>
<li class="active">Edit</li>
{% else %}
<li class="active">Create</li>
{% endif %}
</ol>
{% endblock %}

{% block content %}
<div class="box">
  <div class="box-header with-border">
  <h3 class="box-title">{% trans 'Transaction Details' %}</h3>
</div>
<div class="box-body">
    <form method="post" class="form-horizontal">
      {% csrf_token %}
      {% for field in form %}
        <div class="form-group{% if field.errors %} has-error{% endif %}">
          <label class="col-sm-2 control-label" for="{{ field.id_for_label }}">{{ field.label }}
          </label>
          <div class="col-sm-8">
          {{ field|add_class:"form-control" }}
          {% for error in field.errors %}
          <span class="help-block">{{ error }}</span>
          {% endfor %}
        </div>
        </div>
      {% endfor %}
      <br>
      {% for error in form.non_field_errors %}
      {{ error }}
      {% endfor %}
      {{ formset.management_form }}
      <table id="formset" class="table">
      {% for split in formset %}
        {% if forloop.first %}
        <tr>
          {% for field in split.visible_fields %}
          <th>{{ field.label }}</th>
          {% endfor %}
        </tr>
        {% endif %}
        <tr>
        {% for field in split.visible_fields %}
        {% if field|widget_type == 'checkboxinput' %}
        <td class="text-center">
        {{ field }}
        </td>
        {% else %}
        <td class="form-group{% if field.errors %} has-error{% endif %}">
          {% if 'account' in field.name %}
          {{ field|add_class:"form-control account-input" }}
          {% else %}
          {{ field|add_class:"form-control" }}
          {% endif %}
        </td>
        {% endif %}
        {% endfor %}
        {% for field in split.hidden_fields %}
        {{ field }}
        {% endfor %}
        </tr>
        {% if split.errors %}
        <tr>
          {% for error in split.errors %}
          <span class="help-block">{{ error }}</span>
          {% endfor %}
        </tr>
        {% endif %}
      {% endfor %}
      </table>
      <button type="submit" class="btn btn-primary col-md-offset-2">{% if object %}{% trans 'Update' %}{% else %}{% trans 'Create' %}{% endif %}</button>
      <a id="add-split" class="btn btn-info">{% trans 'Add Split' %}</a>
    </form>
</div>
</div>
{% endblock %}

{% block stylesheets %}
<link rel="stylesheet" href="{% static 'vendor/css/bootstrap-datepicker.min.css' %}">
<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/css/select2.min.css" rel="stylesheet" />
{% endblock %}

{% block scripts %}
<script src="{% static 'vendor/js/bootstrap-datepicker.min.js' %}"></script>
<script src="{% static 'vendor/js/bootstrap3-typeahead.min.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/js/select2.min.js"></script>
<script>
function cloneMore(selector, type) {
    var newElement = $(selector).clone(true);
    var total = $('#id_' + type + '-TOTAL_FORMS').val();
    newElement.find(':input').each(function() {
        var name = $(this).attr('name').replace('-' + (total-1) + '-','-' + total + '-');
        var id = 'id_' + name;
        $(this).attr({'name': name, 'id': id}).val('').removeAttr('checked');
    });
    newElement.find('label').each(function() {
        var newFor = $(this).attr('for').replace('-' + (total-1) + '-','-' + total + '-');
        $(this).attr('for', newFor);
    });
    total++;
    $('#id_' + type + '-TOTAL_FORMS').val(total);
    $(selector).after(newElement);
}
$(function() {
  $('#id_date').datepicker({
  autoclose: true,
  format: 'yyyy-mm-dd',
  endDate: '0d',
  orientation: 'bottom',
  })
  $('#id_date').attr('autocomplete', 'off');
  $('#add-split').click(function() {
    cloneMore('#formset tr:last', 'split');

  });
});

</script>
{% endblock %}

silverstrike/templates/silverstrike/reconcile.html
{% extends 'silverstrike/base.html' %}
{% load i18n %}
{% load static %}
{% load widget_tweaks %}

{% block content_header %}
<h1>{% trans 'Reconcile' %}
  <small>
    {{ account|title }}
  </small>
</h1>
<ol class="breadcrumb">
  <li><a href="/">{% trans 'Home' %}</a></li>
  <li><a href="{% url 'accounts' %}">{% trans 'Accounts' %}</a></li>
  <li><a href="{{ account.get_absolute_url }}">{{ account }}</a></li>
  <li class="active">{% trans 'Reconcile' %}</li>
</ol>
{% endblock %}

{% block content %}
<div class="box">
  <div class="box-header with-border">
  <h3 class="box-title">{% trans 'Create reconcile transaction' %}</h3>
</div>
<div class="box-body">
    <form method="post" class="form-horizontal">
      {% csrf_token %}
      <div class="form-group{% if form.title.errors %} has-error{% endif %}">
        <label class="col-sm-2 control-label" for="{{ form.title.id_for_label }}">{{ form.title.label }}
        </label>
        <div class="col-sm-8">
          {{ form.title|add_class:"form-control" }}
          {% for error in form.title.errors %}
          <span class="help-block">{{ error }}</span>
          {% endfor %}
        </div>
      </div>
      <div class="form-group{% if form.balance.errors %} has-error{% endif %}">
        <label class="col-sm-2 control-label" for="{{ form.balance.id_for_label }}">{{ form.balance.label }}
        </label>
        <div class="col-sm-8">
          {{ form.balance|add_class:"form-control" }}
          <span class="help-block">Current balance: {{ account.balance }}</span>
          {% for error in form.balance.errors %}
          <span class="help-block">{{ error }}</span>
          {% endfor %}
        </div>
      </div>
      <div class="form-group{% if form.notes.errors %} has-error{% endif %}">
        <label class="col-sm-2 control-label" for="{{ form.notes.id_for_label }}">{{ form.notes.label }}
        </label>
        <div class="col-sm-8">
          {{ form.notes|add_class:"form-control" }}
          {% for error in form.notes.errors %}
          <span class="help-block">{{ error }}</span>
          {% endfor %}
        </div>
      </div>
      <button type="submit" class="btn btn-primary col-md-offset-2">{% if object %}{% trans 'Update' %}{% else %}{% trans 'Create' %}{% endif %}</button>
    </form>
</div>
</div>
{% endblock %}

{% block stylesheets %}
<link rel="stylesheet" href="{% static 'vendor/css/bootstrap-datepicker.min.css' %}">
{% endblock %}

{% block scripts %}
<script src="{% static 'vendor/js/bootstrap-datepicker.min.js' %}"></script>
<script src="{% static 'vendor/js/bootstrap3-typeahead.min.js' %}"></script>

<script>
$(function() {
  $('#id_date').datepicker({
  autoclose: true,
  format: 'yyyy-mm-dd',
  endDate: '0d',
  orientation: 'bottom',
  });
  $('#id_date').attr('autocomplete', 'off');
})
</script>
{% endblock %}

silverstrike/templates/silverstrike/recurringtransaction_confirm_delete.html
{% extends 'silverstrike/base.html' %}
{% load i18n %}
{% load widget_tweaks %}

{% block content_header %}
<h1>Delete '{{ object.title }}' recurring transaction
</h1>
{% endblock %}

{% block content %}
<div class="col-md-offset-3 col-md-6">
<div class="box">
  <form method="post" class="form-horizontal">
    <div class="box-body">
      {% csrf_token %}
        <p>Are you sure you want to delete the recurring transaction?</p>
        <div class="text-center">
        <a href="{{ object.get_absolute_url }}" class="btn btn-default">{% trans 'Cancel' %}</a>
        <button type="submit" class="btn btn-danger">{% trans 'Delete' %}</button>
      </div>
    </div>
  </form>

</div>
</div>
{% endblock %}